In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix, accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import GaussianNB

In [2]:
def read_file(filename):
    data = pd.read_csv(filename)
    print(data.shape)
    data['label'] = data['label'].apply(lambda x: x.strip().lower())
    return data

In [3]:
datatrain = 'LGBT_train.csv'
datatest = 'LGBT_test.csv'

In [4]:
data_ho_train = read_file(datatrain)
data_ho_test = read_file(datatest)

(188, 2)
(81, 2)


In [5]:
target_encoder = LabelEncoder()
data_ho_train['targetTR'] = target_encoder.fit_transform(data_ho_train['label'])
data_ho_test['targetTS'] = target_encoder.transform(data_ho_test['label'])
data_ho_train.head()

tweet    label  targetTR
0  ['kenapa', 'negara', 'udah', 'krisis', 'iklim'...  negatif         0
1  ['lgbt', 'lesbian', 'gay', 'biseksual', 'trans...  negatif         0
2    ['nadir', 'wakil', 'lgbt', 'nahdatul', 'ulama']  negatif         0
3                           ['toko', 'jual', 'lgbt']  negatif         0
4  ['sampai', 'monyet', 'telur', 'statement', 'di...  positif         1

In [6]:
x_ho_train = data_ho_train.drop(['tweet','label'], axis=1)
y_ho_train = data_ho_train['targetTR']
#x_ho_train.head()
x_ho_test = data_ho_test.drop(['tweet','label'], axis=1)
y_ho_test = data_ho_test['targetTS']
#x_ho_train.head()

In [7]:
vectorizer = TfidfVectorizer (max_features=2500)
model_g = GaussianNB()

v_data = vectorizer.fit_transform(data_ho_train['tweet']).toarray()
print (v_data)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(v_data, data_ho_train['label'], test_size=0.19, random_state=1)
model_g.fit(X_train,y_train)

GaussianNB()

In [9]:
y_preds = model_g.predict(X_test)

print(confusion_matrix(y_test,y_preds))
print(classification_report(y_test,y_preds))
print('nilai akurasinya adalah ',accuracy_score(y_test, y_preds))

[[22  3]
 [ 4  7]]
              precision    recall  f1-score   support

     negatif       0.85      0.88      0.86        25
     positif       0.70      0.64      0.67        11

    accuracy                           0.81        36
   macro avg       0.77      0.76      0.76        36
weighted avg       0.80      0.81      0.80        36

nilai akurasinya adalah  0.8055555555555556
